# Generated by Django 3.0.8 on 2020-12-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_auto_20201203_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='students',
            name='fcm_token',
        ),
    ]
